services:
  db:
    image: postgres:16-alpine
    container_name: tscommerce-db
    restart: unless-stopped
    networks:
      - devnet
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ts_commerce
    ports:
      - "5410:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U root -d ts_commerce"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

networks:
  devnet:
    driver: bridge
